# Generated by Django 4.2 on 2024-07-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin_user', '0003_adminuserlist_org_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=20)),
                ('tablename', models.CharField(max_length=255, unique=True)),
                ('auth_groundman', models.BooleanField()),
                ('auth_curator', models.BooleanField()),
                ('auth_scorer', models.BooleanField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminuserlist', to='super_admin_user.adminuserlist')),
            ],
        ),
    ]
